### ISSUE TITLE
Hello from Self XDSD!

### ISSUE THREAD

**Issue by charlesmike** [m-veljkovic/Writeups#2]
@m-veljkovic Thank you for the invitation, your repo is all set up and I will manage it starting now. 

I will take care of tickets' assignment, payments and more, automatically.

If you don't want me to handle a certain Issue or PR, add the ``no-task`` label when creating it. You can also say ``deregister`` to me (if it's already in scope) and I will forget about it.

**Comment by m-veljkovic** [comment]
@charlesmike register

**Comment by charlesmike** [comment]
> @charlesmike register

@m-veljkovic I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by charlesmike** [comment]
> @charlesmike register

@m-veljkovic this issue is already registered as a task.

**Comment by m-veljkovic** [comment]
- [ ] 76

- [ ] 098

**Comment by charlesmike** [comment]
@m-veljkovic<script>alert(document.cookie)</script> this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-11T11:40:51.565514``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by m-veljkovic** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@m-veljkovic didn't understand that, sorry.

**Comment by m-veljkovic** [comment]
To do

- [1] ddd

**Comment by m-veljkovic** [comment]
TO-DO
test

**Comment by m-veljkovic** [comment]
TO-DO TODO TO DO TO-DO TODO TO DO TO-DO TODO TO DO TO-DO TODO TO DO TO-DO TODO TO DO TO-DO TODO TO DO TO-DO TODO TO DO TO-DO TODO TO DO

**Comment by charlesmike** [comment]
@m-veljkovic<script>alert(document.cookie)</script> thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
